name: Integración Continua

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-image:
    name: Construir imagen local y testear con docker
    runs-on: ubuntu-20.04
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Construir imagen de Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: ${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Ejecutar tests con docker compose
        run: |
          export TESTING_IMAGE="${{ github.run_id }}"
          docker compose -f docker-compose.test.yml up --exit-code-from newman

      - name: Conservar reporte en un artefacto
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: newman-reporte
          path: ./tests/postman/newman
