on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_IMAGE_NAME: estephany16/pokemon-api

jobs:
  build-image:
    name: Construir imagen local
    runs-on: ubuntu-20.04
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Construir imagen de Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run-tests:
    name: Ejecutar tests
    runs-on: ubuntu-20.04
    needs: [build-image]
    services:
      api:
        image: estephany16/pokemon-api
        ports:
          - 8765:8765

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ejecutar tests con newman
        uses: matt-ball/newman-action@master
        with:
          collection: tests/postman/PokemonPrueba.postman_collection.json
